version: '2.4'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --ISCAgent false
    ports:
      - 1972
      - 7000:52773
    volumes:
      - ./dist:/opt/app/web
